/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package embedded.servlet.demo;

import java.io.File;
import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.catalina.Context;
import org.apache.catalina.LifecycleException;
import org.apache.catalina.WebResourceRoot;
import org.apache.catalina.Wrapper;
import org.apache.catalina.startup.Tomcat;
import org.apache.catalina.webresources.DirResourceSet;
import org.apache.catalina.webresources.StandardRoot;

import embedded.servlet.demo.service.PersonService;

public class App {

    public static void main(String[] args) throws LifecycleException {
        Tomcat server = new Tomcat();
        server.getConnector();
        server.setPort(8080);
        Context context = server.addWebapp("/demo", new File("app/src/main/webapp").getAbsolutePath());
        WebResourceRoot resources = new StandardRoot(context);
        resources.addPreResources(new DirResourceSet(resources, "/WEB-INF/classes",
                new File("app/build/classes/java/main").getAbsolutePath(), "/"));
        context.setResources(resources);

        server.addServlet("/demo", "personServlet", PersonService.class.getName());
        context.addServletMappingDecoded("/api/v1/*", "personServlet");

        Wrapper peopleServlet = server.addServlet("/demo", "peopleServlet", new HttpServlet() {
            @Override
            protected void doGet(HttpServletRequest req, HttpServletResponse resp)
                    throws ServletException, IOException {
                HttpSession session = req.getSession();
                String user = (String) session.getAttribute("user");
                if (user != null && user.equals("admin")) {
                    resp.getWriter().println("Welcome admin");
                } else {
                    user = getInitParameter("user");
                    resp.getWriter().println("Welcome " + user);
                }
            }
        });
        context.addServletMappingDecoded("/people", "peopleServlet");
        peopleServlet.addInitParameter("user", "Anonymous");

        server.addServlet("/demo", "loginServlet", new HttpServlet() {
            @Override
            protected void doPost(HttpServletRequest req, HttpServletResponse resp)
                    throws ServletException, IOException {
                String user, pass;
                if ((user = req.getParameter("user")) != null && ((pass = req.getParameter("pass")) != null)) {
                    if (user.equals("admin") && pass.equals("admin")) {
                        HttpSession session = req.getSession();
                        session.setAttribute("user", user);
                        resp.getWriter().println("Success");
                    } else {
                        resp.sendRedirect("/demo");
                    }
                }
            }
        });
        context.addServletMappingDecoded("/login", "loginServlet");

        server.start();
        server.getServer().await();
    }
}
